eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
server:
  port: 8762
spring:
  thymeleaf:
    prefix: ./templates/
    suffix: .html
    encoding: UTF-8
    cache: false
    content-type: text/html
    mode: HTML5
  application:
    name: service-hi


